### PR TITLE
Toggle missing and known traits for properties and spaces

### PR DESCRIPTION
**Pull request by marswill**
Currently, if you click the properties tab under a given space, you get a list of all properties whose status is known for that space.  This list excludes the unknown traits, so it's hard to know what's missing without scanning the list manually and looking for skipped numbers, then comparing to a full list of properties in another tab or window.

This PR ensures that by default, all traits including missing ones are displayed on the properties tab of a space, and moreover, the user can toggle whether the known and/or unknown traits are displayed.  

This could be a small quality of life improvement for contributors adding properties to a space, so they can quickly filter out the known traits and see which ones are still missing.

Also, this same change is implemented for the spaces tab of a given property.

### CODE REVIEW

**Comment by marswill** [comment]
In retrospect I guess it may have premature to make this a PR given the failed unit tests, which I'll need to look into some more.  Does it make sense to convert to draft for now until that's done?  

In general, would be good to know the protocol in this kind of situation. @StevenClontz any thoughts?

**Comment by StevenClontz** [comment]
I've converted to a draft - this won't be merged until all CI requirements pass, so keeping things in draft format until the PR could be merged is appropriate.

Here, I don't think the issue is that tests are failing. Instead, James has set a threshold for code coverage. So we need to add some new tests to cover the new functionality. Those might wait until the feedback in the thread is addressed.

One quick comment - part of this PR should be a non-404 page for unknown space/property traits. A simple "we don't know, here's how you can contribute if you do" would be nice to start with.

**Comment by marswill** [comment]
Based on forum feedback, will now default to only show known (asserted and Deduced) traits.  User now may toggle Asserted, Deduced, and Missing traits on and off.

> One quick comment - part of this PR should be a non-404 page for unknown space/property traits. A simple "we don't know, here's how you can contribute if you do" would be nice to start with.

Will deal with that as well asap.

**Comment by marswill** [comment]
I've added a replacement for the 404 page, instead inviting contributors to supply missing properties.  I had a random thought that maybe it would be nice to show the related theorems for a property when inviting contributions.  After looking at the result I think maybe that was overkill, but I left it in for now to see what others think.

https://missing-traits.topology.pages.dev/spaces/S000092/properties/P000005

**Comment by prabau** [comment]
To the right of the User icon, there seems to be an "X" icon which shouldn't be there.

**Comment by prabau** [comment]
When I go directly to `https://missing-traits.topology.pages.dev` and then to Spaces or Properties and choose one space or property, the three tabs in that page (Theorems, Spaces, References, etc) are broken due to a double backslash.  For example, it tries to link to `https://missing-traits.topology.pages.dev/properties/P000006//spaces`.

But if I then go to and Advanced page to check the branch and from there repeat the procedure (go to Spaces or Properties, etc) the problem goes away.  No more double backslashes.

**Comment by marswill** [comment]
> For example, it tries to link to https://missing-traits.topology.pages.dev/properties/P000006//spaces.

> Seems unrelated to your change though.

Yes, fwiw I've encountered this issue on the main branch as well, not sure what it's about.

**Comment by StevenClontz** [comment]
> > For example, it tries to link to https://missing-traits.topology.pages.dev/properties/P000006//spaces.
> 
> > Seems unrelated to your change though.
> 
> Yes, fwiw I've encountered this issue on the main branch as well, not sure what it's about.

Can you open an issue on this repository and assign @jamesdabbs and myself to investigate?

**Comment by marswill** [comment]
Unit test coverage has been resolved, but regarding the failed end-to-end tests, I'm at a loss to explain them.  The problematic tests seem to be the cypress tests in [deduction.spec.ts](https://github.com/pi-base/web/pull/133/commits/d529ba8c6451b3fbbfb1701a7a1f8c0080b01d91#diff-4e5059f3806f7d080f4df630198db9d8edc5e2d1a3e32d1494a33dd6148b1780), and they began before I modified that file.

Going to summarize the issue here since it's hard to sift through a decent number of commits.

The end-to-end tests were originally passing when I first did the PR (only unit tests were failing because of coverage issues that have since been resolved), and failed for the first time when I dealt with with the 404 issue in this commit:

8aae6bd075937f0b5060c74bbdcf6c7f5d05432e

At that time, the first two tests passed, the third timed out looking for "251", and the fourth (testing the converse of theorem T10) passed, which seemed odd since it was clearly outdated (we updated theorem T10 a week or two ago so its converse is no longer true).

I thought maybe the outdated theorem might be the problem anyway, so changed it in this commit:

d529ba8c6451b3fbbfb1701a7a1f8c0080b01d91

The result was that now the third and fourth tests both timed out, looking for "251" and "335" respectively.

Finally in the very last commit I've made so far, which was to remove the theorem list from the missing trait page, the second, third and fourth tests in deduction.spec.ts all failed, the second timing out before finding "T1", the third before "paracompact" (as opposed to "251" on previous tries), and the fourth before "335":

4739e980992f3c4586cdd20d42873b39e00c8577

**Comment by prabau** [comment]
Trying out your new layout.  The plethora of buttons makes things confusing at first.  But after a little bit of playing with it, one can figure it out.  A few comments:

- We cannot show only the deduced anymore.  That's fine with me actually, as that's not a common use case.
- The default when you land on a space page is to display only the properties with value = true.  I think the default should be to show both true and false (= check and X).
- The relationship between the buttons (check and X), (check only), (X only) is confusing, because they are separated by the (user) button.  The order (check and X, check, X, user, question)  would be clearer, I think.
- Before we had three categories (asserted, deduced, unknown) and they could be toggled independently.  In that context, the button were labelled "Show ..." or "Hide ...", which made sense.  In the new model, we have a choice of 6 states, and we toggle between them by choosing the appropriate button.  But "Show"/"Hide" does not quite make sense in that framework anymore.  How about keeping the first button as "Show all" and having just the icons (check and X, check, X, user, question) without the word "Shows" for the other ones?

**Comment by prabau** [comment]
I like it.

@ccaruvana, @StevenClontz what do you think?

**Comment by StevenClontz** [comment]
@marswill I'm working on the e2e tests now

**Comment by StevenClontz** [comment]
My guess is that the e2e tests are seeing the new "we could not deduce this" page that appears before the deductions actually run. I bet there's a way to make it more patient, but perhaps it's better to figure out how to wait for the deductions to run before "loading" any space/property pair.

**Review by StevenClontz — APPROVED** [review]

**Pull request merged**
