### PR TITLE
Display aliases on Explore page

### PR DESCRIPTION
**Pull request by StevenClontz**
See https://github.com/pi-base/data/issues/792

### CODE REVIEW

**Comment by StevenClontz** [comment]
@prabau thoughts?

**Comment by StevenClontz** [comment]
image

**Comment by StevenClontz** [comment]
The fact "cantor space" doesn't show up first for "cantor" is addressed here: https://github.com/pi-base/web/pull/178

**Comment by prabau** [comment]
The search filtering both by formula and by text does not work as expected.  When searching for compact spaces related to "Cantor", one get things like S19, S20, which are compact but have nothing to do with "Cantor", even with fuzzy matching.  It seems that there is a flaw in the algorithm here.

Even searching for "cantor" without specifying properties returns spaces like Euclidean real numbers, Irrational numbers, Altered long ray, etc that have nothing to do with "cantor", 43 spaces in total.

Ordering the results by closest match when searching by text does not seem a bad idea, but the problem above is much more serious and should be looked at.

**Comment by prabau** [comment]
As for displaying the alias for spaces, would that apply only when filtering by text (with or without also filtering by formula)?
When not filtering by text, it's maybe preferable not to use it because it occupies more real estate and there is no need to.  When filtering by text, it could be ok.

Another thing that the sample screenshot above points to is the inadequacy of many of the current aliases.
Just taking S36 (Successor to the first uncountable ordinal) as an example, we have aliases like "Omega1 + 1" and "ω_1 + 1" and ... Several of these aliases date from way back, when we could not render LaTex in aliases.  But that has changed.  Some of the other aliases may also be debatable.

I think it would be beneficial to discuss in general terms how to improve the aliases, and also the search issue above.  A good topic for next zoom meeting.

**Comment by StevenClontz** [comment]
> When not filtering by text, it's maybe preferable not to use it because it occupies more real estate and there is no need to.

I thought about this, but I still think that if we have relegated the name of a space to an alias that a user expects, it's still good to have it handy so they can quickly find a space they are familiar with, even if we use a different canonical name than they are used to.

> inadequacy of many of the current aliases

Absolutely agreed - if we're going to display aliases this prominantly, we should also clean up some less-useful ones. I like discussing this next month.

**Comment by prabau** [comment]
> I thought about this, but I still think that if we have relegated the name of a space to an alias that a user expects, it's still good to have it handy so they can quickly find a space they are familiar with, even if we use a different canonical name than they are used to.

Maybe.  Although when you filter only by formula, you are interested in just a list of spaces matching the criteria.  Then the user can just click on things that look interesting and they will find more detail of each space if they want to.  It does not matter that the name is not the one they are used to.  After drilling down, they will find more details.  Anyway, we can discuss further in the zoom meeting.

**Comment by GeoffreySangston** [comment]
Is there a way that the 'Filter by formula' drop down can indicate when a property / space is appearing because it almost matches one of the aliases? The word 'Alias' could appear in the bottom right of the box, or the box could be colored light green. Or perhaps better, instead of displaying the name in the 'Filter by formula' drop down box, it could just display the matching alias.

(Funnily enough, I briefly couldn't find limit point compact yesterday because the name is now weakly countably compact, and I just saw this was also discussed recently.)

**Comment by StevenClontz** [comment]
Adding aliases to the formula suggestion box might be the simplest solution here:

image

**Comment by prabau** [comment]
@GeoffreySangston @StevenClontz While is was true that the aliases were not displayed in the search box, they were looked at as part of the search.  We should discuss more today in the zoom meeting.

**Comment by StevenClontz** [comment]
Thanks everyone for your feedback in today's community call. I'm deploying to production now; let me know your feedback and we can iterate from here.

**Comment by prabau** [comment]
This is a nice improvement.  The adjustment of the threshold for searching by space name/alias in the Explore page really helped narrow down the result as desired.

Next step: make the corresponding adjustment for the search box in the Spaces page.

**Comment by GeoffreySangston** [comment]
I guess this might be a good place to mention this.

On [the properties page](https://topology.pi-base.org/properties), cmd + F shows are 6 properties which just give "Any of the following equivalent properties holds:", followed by a block of equivalent definitions. I think we should move the top line of each block to the top.

**Comment by prabau** [comment]
> I guess this might be a good place to mention this.
> 
> On [the properties page](https://topology.pi-base.org/properties), cmd + F shows are 6 properties which just give "Any of the following equivalent properties holds:", followed by a block of equivalent definitions. I think we should move the top line of each block to the top.

I think the most important thing is to have a clear and coherent text on each property page.  What is displayed in the Properties list is not very important.  So I may not agree with this.  Can we make this an item of discussion for the next community meeting?

**Comment by StevenClontz** [comment]
I actually lean towards @GeoffreySangston's suggestion that having one common characterization in the top line would be nice to show up in previews, and we can also include it in a list of equivalent characterziations in a fuller description (so it's not missed there either).

**Pull request merged**
