### PR TITLE
fix: ?property formula, resolve #205

### LINKED ISSUE #205: Buggy ?property formula
https://topology.pi-base.org/spaces?q=LOTS%2BPerfectly+normal%2B%3FFirst+Countable

image

See converation at https://github.com/pi-base/data/issues/1041

### PR DESCRIPTION
**Pull request by yhx-12243**
I don't know how to add an appropriate test for this PR. But it works in my environment.

### CODE REVIEW

**Comment by StevenClontz** [comment]
Preview at https://pr206.topology.pages.dev/

**Comment by StevenClontz** [comment]
There could be further improvements:

image

should show more than just a single theorem (it should show the whole proof that second countable implies first countable). But I think this is a strict improvement for the scenarios like the one you suggest and will merge as-is.

cc @jamesdabbs

**Review by StevenClontz — APPROVED** [review]

**Comment by yhx-12243** [comment]
Yes I've just discovered there are still some faults in `Derivations::expand`, and it may need to resolved later 😭

**Comment by StevenClontz** [comment]
No problem, thanks for the patch in any case!

**Comment by StevenClontz** [comment]
I'm not seeing the issue you refer to @prabau. Can you give a specific example of a search that's now broken?

**Comment by yhx-12243** [comment]
I'm not understand what you mean, can you give us an example?

**Comment by prabau** [comment]
[π-Base, Search for `LOTS + ?First countable`](https://topology.pi-base.org/spaces?q=LOTS+%2B+%3FFirst+countable)

Now it says "No spaces found satisfying [LOTS](https://topology.pi-base.org/properties/P000133) ∧ ?[First countable](https://topology.pi-base.org/properties/P000028)"

Previously it said: "... is impossible".

**Comment by yhx-12243** [comment]
> There could be further improvements:
> 
> image
> 
> should show more than just a single theorem (it should show the whole proof that second countable implies first countable). But I think this is a strict improvement for the scenarios like the one you suggest and will merge as-is.
> 
> cc @ jamesdabbs

I think https://github.com/yhx-12243/pi-base-web/commit/ab7c5f04bef15fd744ca259aaad2a94961624961 will resolve this. Anyway, e.g., `?GO-space + Perfectly normal + ~First Countable` cannot be deduced because the deduction of `GO-space + Perfectly normal + ~First Countable` need the multiple usage of `GO-space`. This is a intrinsic defect of our deduction system, just shown in #199.

But after the patch above, `LOTS + Perfectly normal + ?First Countable` will show the correct output as `LOTS + Perfectly normal + ~First Countable`, and it can be further checked and slowly merged.

Screenshot 2024-12-10 11 10 25

**Comment by yhx-12243** [comment]
> [π-Base, Search for `LOTS + ?First countable`](https://topology.pi-base.org/spaces?q=LOTS+%2B+%3FFirst+countable)
> 
> Now it says "No spaces found satisfying [LOTS](https://topology.pi-base.org/properties/P000133) ∧ ?[First countable](https://topology.pi-base.org/properties/P000028)"
> 
> Previously it said: "... is impossible", which is exactly the case here.

Because, it is not impossible at all. There LOTS spaces first countable and not first countable, this is because the fault of the previous deduction system.

**Comment by prabau** [comment]
Yes, that will be much better.

**Comment by prabau** [comment]
As an alternative to giving the full deduction, one might output a summary, namely in this case:
LOTS + perfectly normal => first countable.

But that's probably too much.  So some full deduction it still ok, and the user has to figure out what the summary is.

**Comment by prabau** [comment]
About the above, I think I got confused with a wrong example.  What I meant to use was:

[π-Base, Search for `LOTS + Perfectly normal + ?First Countable`](https://topology.pi-base.org/spaces?q=LOTS+%2B+Perfectly+normal+%2B+%3FFirst+Countable)

Before, it was saying "... is impossible".  And it still says the same thing.  So that's fine.

**Comment by prabau** [comment]
So basically, the current PR #206 is nice and solves an issue.

But it's independent of #205 and does not address #205, which was about confusing and incomplete output for the user.

**Comment by StevenClontz** [comment]
Agreed, it does not resolve #205 completely, so I will keep #205 re-opened.

**Comment by StevenClontz** [comment]
> because the first is merged too fast 😂

[image](https://xkcd.com/1428/)

But of course, please mark PRs as a draft if they are indeed in progress! Thanks again for the work here @yhx-12243.

**Pull request merged**
